### ISSUE TITLE
Colab wrong command?

### ISSUE THREAD

**Issue by p0mad** [davidpagnon/Sports2D#3]
Hi @davidpagnon
I've checked your colab notebook placed [here ](https://colab.research.google.com/github/davidpagnon/Sports2D/blob/main/Sports2D/Sports2D.ipynb)
and i found that it might have some wrong command! (not sure if the openpose is checkedout to specific tag or not)

!sed -i 's/execute_process(COMMAND git checkout master WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}\/3rdparty\/caffe)/execute_process(COMMAND git checkout f019d0dfe86f49d1140961f8c7dec22130c83154 WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}\/3rdparty\/caffe)/g' openpose/CMakeLists.txt

This line of code do noting actually!

here is my clone of openpose (today) without checkout, and i can see that openpose/CMakeLists.txt containes lines with `git checkout master` but all of them are commented out!
![image](https://github.com/davidpagnon/Sports2D/assets/131435526/01d851ae-2873-496d-b34b-f7c8fe3ad7ae)

either this command is not needed or needs to be modified for replacing the 1807aad with f019d0d for caffe!

Also does it needs to install opencv as a requirement?( i think the openpose > V1.6.0  do not needs the opencv while with the available code on a native ubuntu system, it askes for opencv while making it with the default CMakeList.txt file!

Thanks
Best regards

**Comment by p0mad** [comment]
This is the cmake error 
![image](https://github.com/davidpagnon/Sports2D/assets/131435526/dff0f77c-8244-4f24-ab37-835e5e93ba1e)

have you check out into specific version of openpose?

**Comment by davidpagnon** [comment]
If I understand well, you are trying to run the Colab code on a local Ubuntu station? 

While both setups are quite similar, a standard Ubuntu installation does not come with as many libraries. 

For example, OpenCV is natively installed on Colab and I did not bother install it again. You will likely need to install it on your computer (see the paragraphs coming right after your make error for indications about how to do that). 

To be honest, I took most of the code from [there](https://colab.research.google.com/github/tugstugi/dl-colab-notebooks/blob/master/notebooks/OpenPose.ipynb) and adapted it because it was buggy. I'm not an expert in building project but I'm pretty sure the line of code you're referring to is replacing `master` with the specific version `f019d0dfe86f49d1140961f8c7dec22130c83154` in the CMakeLists.txt file.

**Comment by p0mad** [comment]
> I'm pretty sure the line of code you're referring to is replacing `master` with the specific version `f019d0dfe86f49d1140961f8c7dec22130c83154` in the CMakeLists.txt file

This defenately replaces master with f019d0 but as the line including "maste" is commented out, So it does notting! you can ommit this line and test the code!

Thanks for refering to the original code

I've also installed opencv but make -j`nproc` troughs an error about boost library!
Thats annoying!

**Comment by davidpagnon** [comment]
Okay I understand what you mean. Did you try replacing `1807aad` with the other version? The other version has been tested and works, but apparently it is not needed since it made a change on a commented line. 

Concerning the Opencv issue, I am sorry, I don't have a lot of time this week, and I'm not even sure I can help you since I don't have a lot of experience in building with Cmake. I usually just try to change little things until it works, which is definitely not the best way to proceed... 

Do you have anyone in your team that could help you? If not, hit me up in a little while (and if so, maybe you could just use the Colab version, which works?)

**Comment by davidpagnon** [comment]
Hi @p0mad ,
(very) long story short, the colab version should be up now! Don't hesitate to tell me if you face any issues.
I'm closing this for now but if you experience any problems, please reopen the issue.
