### ISSUE TITLE
Joint Angle Overlay Video Issue

### ISSUE THREAD

**Issue by 24victorl** [davidpagnon/Sports2D#6]
For some reason, the joint angle annotations appear sped up and 'chopped up' during playback. Is there a specific format or setting that optimizes the video output for smooth playback?

**Comment by davidpagnon** [comment]
Hi Victor,
Do you mean that frames are not in the right order? Could you attach a video so that I can see what is going on?

**Comment by davidpagnon** [comment]
Thank you for sending me the video. This is strange, I just tried it and it works fine on my end. Which version did you use? The colab, or the local one?
Do you use Windows, Mac, Linux?
Can you send me your whole Demo folder so that I can help trouble shoot it?

**Comment by davidpagnon** [comment]
So I had a look at your data, the csv files are okay and output images are in the right order. The issue comes when it wants to make a video out of it. This is a known issue with cv2.VideoWriter on macOS, but unfortunately, I could not find a way to solve it (and I cannot spend much time on it).

Just remember you can trust the images and the csv files (although BlazePose is not the best pose estimator).
If you need to create videos, I would advise you to try this method: https://support.apple.com/guide/quicktime-player/create-a-movie-with-an-image-sequence-qtp315cce984/mac

**Comment by davidpagnon** [comment]
@24victorl I know it is pretty late, but I think I fixed the issue of mixed-up frames when generating videos (and the Colab version should be working, too). If you are still on it, please tell me if this is okay on your end!

**Comment by davidpagnon** [comment]
I'm closing it for now but if it does not work feel free to reopen it
