### ISSUE TITLE
Results from Vertical Movement instead of Left to Right

### ISSUE THREAD

**Issue by 24victorl** [davidpagnon/Sports2D#7]
I was also wondering if the Sports2D model can still accurately track and analyze such vertical dynamics (Warning section says it's only lateral). Also are there any specific parameters/settings that I can change to get the accurate coordinates/joint angles from a vertical movement?

**Comment by davidpagnon** [comment]
Hi Victor, 

The accuracy is limited by the 2D pose estimation model. BlazePose is not very accurate, OpenPose is better but far from perfect. If you want something really accurate, you need several cameras and to constrain coordinates to a biomechanical model. In case you have time for it, I wrote the package [PoseSim]( https://github.com/perfanalytics/pose2sim) that does all of that. Sports2D is meant more for coaches who want to obtain an estimated result without too much of a hassle.

That being said, if you want the elevation of the center of gravity, you can take your "points.csv" file (eg demo_BLAZEPOSE_points.csv) and look for the y coordinate of LHip or RHip. This will be in pixels rather than in meters though.

**Comment by davidpagnon** [comment]
To be more specific, it does not really matter whether the person is filmed from the side or from the front. The only thing is that Sports2D will consider that a joint can move along only one angle, so if you look from the side, the hip movement will be hip flexion/extension, and from the front it will be hip ab/adduction.

**Comment by davidpagnon** [comment]
This issue has been closed as stale. Feel free to reopen it if needed.
